language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "node"
after_success:
  - ./node_modules/.bin/istanbul cover -x "tests-es5/**.js" ./node_modules/.bin/_mocha tests/index.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
